# Generated by Django 5.2.7 on 2026-03-10 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CongeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_absence', models.CharField(choices=[('conge_paye', 'Congé payé'), ('maladie', 'Maladie'), ('sans_solde', 'Sans solde'), ('formation', 'Formation'), ('autre', 'Autre')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='employes.employe')),
            ],
            options={
                'db_table': 'conges_absences',
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pointage', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('horodatage', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.CharField(choices=[('normal', 'Normal'), ('mission', 'Mission'), ('heures_sup', 'Heures supplémentaires'), ('rattrapage', 'Rattrapage')], default='normal', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('latitude_pointage', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude_pointage', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_bureau', models.IntegerField(blank=True, null=True)),
                ('dans_zone', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='employes.employe')),
            ],
            options={
                'db_table': 'pointages',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='SeanceTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_entree', models.TimeField()),
                ('heure_sortie', models.TimeField(blank=True, null=True)),
                ('duree_minutes', models.IntegerField(blank=True, null=True)),
                ('est_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='employes.employe')),
                ('pointage_entree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seance_entree', to='pointages.pointage')),
                ('pointage_sortie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seance_sortie', to='pointages.pointage')),
            ],
            options={
                'db_table': 'seances_travail',
                'ordering': ['-date', '-heure_entree'],
            },
        ),
    ]
